stages:
  - Build
  - Testing
  - Release

repack:
  stage: Build
  # trigger: 
  #   - abris-lab/abris-free-server
  #   - abris-lab/abris-ui
  when: always
  script: 
    - chmod +x ./repack.sh
    - ./repack.sh
    - cp /tmp/abris-free/dist ./
  artifacts:  
    when: on_success
    name: 'abris-free'
    paths:
    - ./dist/*
    expire_in: never
  tags:
    - shell
  # allow_failure: false # Отключение обязательности репака

build:
  stage: Build
  when: manual
  script:
    - docker pull abrissite/abris-free
    - docker ps -aq --filter "name=abris_free" | grep -q . && docker stop abris_free && docker rm -fv abris_free
    - docker run -d -it --name abris_free -p 8030:80 -p 45432:5432 abrissite/abris-free
    - sleep 30s # Ожидание воскрешения веб-морды. Обеспечение работоспособности тестов.
  tags:
    - shell
  allow_failure: false

testing:
  stage: Testing
  when: on_success
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd f-tests
    - env TEST_PAGE_ADDRESS=http://abris.site:8030 /opt/testcafe/docker/testcafe-docker.sh chromium -S -s /tmp/host-server-docs/abris-free ./tests 
  except: 
    - tags

release:
  stage: Release
  when: on_success
  before_script:
    - chmod +x ./release.sh
  script:
    - ./release.sh
  only:
    refs:
      - master
    changes:
      - "release_description.md"