stages:
  - Build
  - Testing

build:
  stage: Build
  when: manual
  script:
    - docker pull abrissite/abris-free
    - docker ps -q --filter "name=abris_free" | grep -q . && docker stop abris_free && docker rm -fv abris_free
    - docker run -d -it --name abris_free -p 8030:80 -p 45432:5432 abrissite/abris-free
    - sleep 30s # Ожидание воскрешения веб-морды. Обеспечение работоспособности тестов.
  tags:
    - shell
  allow_failure: false

repack:
  stage: Build
  # trigger: 
  #   - abris-lab/abris-free-server
  #   - abris-lab/abris-ui
  when: on_success
  script: 
    - chmod +x ./repack.sh
    - ./repack.sh
  tags:
    - shell
  # allow_failure: false # Отключение обязательности репака

testing:
  stage: Testing
  when: on_success
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd f-tests
    - env TEST_PAGE_ADDRESS=http://abris.site:8030 /opt/testcafe/docker/testcafe-docker.sh chromium -S -q -s /tmp/host-server-docs/abris-free tests 
  except: 
    - tags