stages:
  - Build
  - Testing

build:
  stage: Build
  when: manual
  script:
    - docker pull abrissite/abris-free
    - docker stop abris-free
    - docker rm abris-free
    - docker run -d -it --name abris-free -p 8030:80 -p 45432:5432 abrissite/abris-free
    - sleep 30s # Ожидание воскрешения веб-морды. Обеспечение работоспособности тестов.
  tags:
    - shell
  allow_failure: false

repack:
  stage: Build
  when: manual
  script: 
    - chmod 777 ./repack.sh
    - ./repack.sh
  tags:
    - shell
  allow_failure: false

testing:
  stage: Testing
  when: on_success
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd f-tests
    - env TEST_PAGE_ADDRESS=http://abris.site:8030 /opt/testcafe/docker/testcafe-docker.sh chromium -S -q -s /tmp/host-server-docs/abris-free tests 
  except: 
    - tags