stages:
  - Build
  - Testing

build:
  stage: Build
  when: manual
  script:
    - docker pull abrissite/abris-free
    - docker stop abris-free
    - docker rm abris-free
    - docker run -d -it --name abris-free -p 8030:80 -p 45432:5432 abrissite/abris-free
    - sleep 30s # Ожидание воскрешения веб-морды. Обеспечение работоспособности тестов.
  tags:
    - shell
  allow_failure: false

repack:
  stage: Build
  when: manual
  script: 
    - cd /tmp/abris-free && rm -Rf ./*
    - "curl --location --header \"PRIVATE-TOKEN: ${CI_API_TOKEN}\" \"https://abris.site:8091/api/v4/projects/5/jobs/artifacts/master/download?job=build-free\""
    - unzip ./abris-ui.zip
    - "curl --location --header \"PRIVATE-TOKEN: ${CI_API_TOKEN}\" \"https://abris.site:8091/api/v4/projects/69/jobs/artifacts/master/download?job=build\""
    - cd ./dist/ && unzip ./abris-server-base.zip
    - cd ../ && zip -r abris-free.zip ./dist/*
    - mv abris-free.zip /var/www/comsite/data/www/abrisplatform.com/downloads/
  tags:
    - shell
  allow_failure: false

testing:
  stage: Testing
  when: on_success
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd f-tests
    - env TEST_PAGE_ADDRESS=http://abris.site:8030 /opt/testcafe/docker/testcafe-docker.sh chromium -S -q -s /tmp/host-server-docs/abris-free tests 
  except: 
    - tags

